### ISSUE TITLE
Sleepio available on NHS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sleep#2]
But only in certain areas... otherwise it's $300 or £200/year...
www.nhs.uk/Conditions/online-mental-health-services/Pages/sleepio.aspx

**Comment by nelsonic** [comment]
I signed up for sleepio and went through their "on boarding" process:
![screen shot 2017-01-14 at 05 04 58](https://cloud.githubusercontent.com/assets/194400/21952614/fee2fccc-da19-11e6-987a-5e6565c1c7cb.png)

The conclusion was:
![screen shot 2017-01-14 at 05 17 34](https://cloud.githubusercontent.com/assets/194400/21952606/d9239b22-da19-11e6-9d7d-fbca7c265f68.png)

And that I'm "_(way) below average_" for my age:
![screen shot 2017-01-14 at 05 17 49](https://cloud.githubusercontent.com/assets/194400/21952609/dc05cb1c-da19-11e6-9431-7d7727a7e287.png)

Which means I should _logically_ jump at the chance to pay "_**less than $1 per day**_:
![screen shot 2017-01-14 at 05 21 38](https://cloud.githubusercontent.com/assets/194400/21952611/e051c8b0-da19-11e6-9de2-a611884fa9cb.png)

_to **fix** my problem..._":
![screen shot 2017-01-14 at 05 21 58](https://cloud.githubusercontent.com/assets/194400/21952632/57576e6a-da1a-11e6-9aac-5c77b3ed28ae.png)

Instead I signed up to be on their "_research list_":
![screen shot 2017-01-14 at 05 22 12](https://cloud.githubusercontent.com/assets/194400/21952635/5c3bc46c-da1a-11e6-8bb9-c0e438eb5014.png)

And wait for them to get back to me...
![screen shot 2017-01-14 at 05 22 20](https://cloud.githubusercontent.com/assets/194400/21952636/643c55aa-da1a-11e6-8f7b-6ebb93b8a026.png)

I don't _understand_ why they don't make it _free_... or at least at a price point that doesn't "prey" on the desperation of people who are suffering.

**Comment by ghost** [comment]
I guess you have to weigh up the market-rate cost of:
+ Cognitive behavioural sleep therapy from a trained therapist
+ Sleeping pills and other alternative medicinal options (for life?)

^potentially cheaper than these?

You need to assess the `real` cost and `opportunity` cost of sleep deprivation and its affects on your life and weigh that against the `product` cost - only you know the answer if it's worth it or not!

**Comment by nelsonic** [comment]
@markwilliamfirth i'm _fairly_ certain the cost of sleepio is worth it. 👍

**Comment by ghost** [comment]
@nelsonic it says "certain areas", maybe your GP is one of those included? Maybe check with GP or hello@sleepio.com

**Comment by nelsonic** [comment]
@markwilliamfirth it's on my list for speaking to GP next appointment on 15th Feb. 👍

**Comment by nelsonic** [comment]
http://www.rankedhealth.com/review/sleepio
![image](https://user-images.githubusercontent.com/194400/34466935-c309a25a-eedb-11e7-9bd4-6f8496576534.png)
While it's not _ideal_ that the "randomized controlled trial" was conducted by the co-founder of the company ... 🙄 
Prof Colin Espie is legit https://en.wikipedia.org/wiki/Colin_Espie
I just wish he didn't feel the need to "get rich" out of his research.
i.e. Sleepio could benefit _way_ more people if they made it a "non-profit".

**Comment by iteles** [comment]
Or even if they just made it accessible. 

I'd pay £52 a year for it like Headspace for example, but certainly not $400 😕
