### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by ghost** [dwyl/sleep#6]
https://justgetflux.com/

+ Your body has a natural body clock (circadian rhythm) that is affected by the sun
+ The blue spectrum of artificial light from computer screens can mimic the affect the sun has
+ Flux reduces blue light emitted from computer screens during the nighttime
+ Blue light affects melatonin production and disrupts natural circadian rhythms and sleep cycles
+ Therefore flux can improve sleep management

It's free!

**Comment by karinakozarova** [comment]
Check out https://iristech.co.

**Comment by nelsonic** [comment]
GOTO: https://support.apple.com/en-us/HT207513
